apiVersion: v1
kind: Service
metadata:
  name: flask-service  # This is the name you'll use in `minikube service`
spec:
  selector:
    app: flask-app  # Must match the label in deployment.yaml
  ports:
    - protocol: TCP
      port: 80       # External port
      targetPort: 5000  # Matches containerPort
  type: LoadBalancer